-- MySQL Script generated by MySQL Workbench
-- Mon Sep 11 09:06:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Farmacia` DEFAULT CHARACTER SET utf8 ;
USE `Farmacia` ;

-- -----------------------------------------------------
-- Table `Farmacia`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Proveedor` (
  `id` INT(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Cliente` (
  `id` INT(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Empleado` (
  `id` INT(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `salario` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Pedido` (
  `id` INT(20) NOT NULL,
  `fecha_pedido` DATE NULL,
  `estado_pedido` INT(20) NULL,
  `Empleado_id` INT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pedido_Empleado1_idx` (`Empleado_id` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id`)
    REFERENCES `Farmacia`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Empleado1`
    FOREIGN KEY (`Empleado_id`)
    REFERENCES `Farmacia`.`Empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farmacia`.`Medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmacia`.`Medicamento` ;

CREATE TABLE IF NOT EXISTS `Farmacia`.`Medicamento` (
  `id` INT(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` DOUBLE NULL,
  `cantidad_stock` INT(50) NULL,
  `fecha_caducacion` DATE NULL,
  `Proveedor_id` INT(20) NOT NULL,
  `Pedido_id` INT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Medicamento_Proveedor1_idx` (`Proveedor_id` ASC) VISIBLE,
  INDEX `fk_Medicamento_Pedido1_idx` (`Pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_Medicamento_Proveedor1`
    FOREIGN KEY (`Proveedor_id`)
    REFERENCES `Farmacia`.`Proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamento_Pedido1`
    FOREIGN KEY (`Pedido_id`)
    REFERENCES `Farmacia`.`Pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
